CREATE SCHEMA Company;
USE Company;

CREATE TABLE DEPARTMENT (
	Dname VARCHAR(20) NOT NULL,
	Dnumber INT NOT NULL,
    -- Mgr_ssn should can be NULL (foreign key), but the textbook set NOT NULL (it set ON DELETE DEFAULT, page 185)
    -- Looks like InnoDB cannot use ON DELETE SET DEFAULT or ON UPDATE SET DEFAULT
    Mgr_ssn CHAR(9),
    Mgr_start_date DATE,
    PRIMARY KEY(Dnumber)
);

CREATE TABLE EMPLOYEE (
	Fname VARCHAR(20) NOT NULL,
	Minit CHAR,
    Lname VARCHAR(20) NOT NULL,
    Ssn CHAR(9) NOT NULL,
    Bdate DATE,
    Address VARCHAR(50),
    Sex CHAR,
    Salary DECIMAL(10, 2),
    Super_ssn CHAR(9),
	-- Dno should can be NULL (FK), but the textbook set NOT NULL (it set ON DELETE DEFAULT, page 185)
    Dno INT,
    PRIMARY KEY(Ssn)
);

CREATE TABLE PROJECT (
	Pname VARCHAR(20) NOT NULL,
    Pnumber INT NOT NULL,
    Plocation VARCHAR(20),
    -- Dnum should can be NULL (FK), but the textbook set NOT NULL (it set ON DELETE DEFAULT, page 185)
    Dnum INT,
    PRIMARY KEY(Pnumber)
);

CREATE TABLE DEPENDENT(
	Essn CHAR(9) NOT NULL,
    Dependent_name VARCHAR(20) NOT NULL, 
    Sex CHAR,
    Bdate DATE,
    Reletionship VARCHAR(20),
    PRIMARY KEY(Essn, Dependent_name)
);

CREATE TABLE DEPT_LOCATIONS(
	Dnumber INT NOT NULL,
    Dlocation VARCHAR(20) NOT NULL,
    PRIMARY KEY(Dnumber, Dlocation)
);

CREATE TABLE WORKS_ON(
	Essn CHAR(9) NOT NULL,
    Pno INT NOT NULL,
    Hours FLOAT(2),
    PRIMARY KEY(Essn, Pno)
);

ALTER TABLE DEPARTMENT
	ADD CONSTRAINT DEPARTMENT_Mgr_ssn_fk
		FOREIGN KEY(Mgr_ssn) REFERENCES EMPLOYEE(Ssn)
			ON DELETE SET NULL
            ON UPDATE CASCADE,
	ADD CONSTRAINT DEPARTMENT_unique
		UNIQUE (Dname);

ALTER TABLE EMPLOYEE
	ADD CONSTRAINT EMPLOYEE_Super_Ssn_fk 
		FOREIGN KEY(Super_Ssn) REFERENCES EMPLOYEE(Ssn)
			ON DELETE SET NULL
            ON UPDATE CASCADE,
	ADD CONSTRAINT EMPLOYEE_Dno_fk
		FOREIGN KEY(Dno) REFERENCES DEPARTMENT(Dnumber)
			ON DELETE SET NULL
            ON UPDATE CASCADE;

ALTER TABLE PROJECT
	ADD CONSTRAINT PROJECT_Dnum_fk
		FOREIGN KEY(Dnum) REFERENCES DEPARTMENT(Dnumber)
			ON DELETE SET NULL
            ON UPDATE CASCADE,
	ADD CONSTRAINT PROJECT_unique
		UNIQUE(Pname);

ALTER TABLE DEPENDENT
	ADD CONSTRAINT DEPENDENT_Essn_fk
		FOREIGN KEY(Essn) REFERENCES EMPLOYEE(Ssn)
			ON DELETE CASCADE
            ON UPDATE CASCADE;

ALTER TABLE DEPT_LOCATIONS
	ADD CONSTRAINT DEPT_LOCATIONS_Dnumber_fk
		FOREIGN KEY(Dnumber) REFERENCES DEPARTMENT(Dnumber)
			ON DELETE CASCADE
            ON UPDATE CASCADE;

ALTER TABLE WORKS_ON
	ADD CONSTRAINT WORKS_ON_Essn_fk
		FOREIGN KEY(Essn) REFERENCES EMPLOYEE(Ssn)
			ON DELETE CASCADE
            ON UPDATE CASCADE,
	ADD CONSTRAINT WORKS_ON_Pno_fk
		FOREIGN KEY(Pno) REFERENCES PROJECT(Pnumber)
			ON DELETE CASCADE
            ON UPDATE CASCADE;